name: Build Maven project
description: 'Build maven project with Quarkus and Java 21'
inputs:
  dockerfile_path:
    description: "Path to the Dockerfile"
    required: false
    default: "Dockerfile"
  image-name:
    description: "name of the image"
    required: false
    default: "academy"
  tag-name:
    description: "name of the tag"
    required: false
runs:
  using: 'composite'
  steps:
    - name: define Tag name
      run: |
        if [ -z "${{ inputs.tag-name }}" ]; then
          echo "TAG=$(date +%s)" >> $GITHUB_ENV
        else
          echo "TAG=${{ inputs.tag-name }}" >> $GITHUB_ENV
        fi
      shell: bash

    - name: define image name
      run: echo "DOCKER_IMAGE_NAME=${{inputs.image-name}}:${{env.TAG}}" >> $GITHUB_ENV
      shell: bash

    - name: build Docker
      run: docker build . --file ${{inputs.dockerfile_path}} --tag ${{inputs.image-name}}:${{env.TAG}}
      shell: bash

    - name: list Docker images
      run: docker image ls
      shell: bash
