--CREATE TYPE rack_status_enum AS ENUM ('ACTIVE', 'RETURNED', 'REPAIR', 'OUTDATED', 'BRICKED');

CREATE TABLE T_TEAM(
   id  BIGINT DEFAULT random() PRIMARY KEY,
   product VARCHAR(30),
   name VARCHAR(50) NOT NULL,
   default_location VARCHAR(10),
   created_at TIMESTAMP,
   modified_at TIMESTAMP
);
CREATE SEQUENCE IF NOT EXISTS SEQ_TEAM_ID START WITH 1 INCREMENT BY 1;

CREATE TABLE T_TEAM_MEMBER(
      id BIGINT DEFAULT random() PRIMARY KEY,
      team_id BIGINT REFERENCES T_TEAM(id),
      ctw_id VARCHAR(10) NOT NULL,
      name VARCHAR(30),
      created_at TIMESTAMP DEFAULT NOW(),
      modified_at TIMESTAMP DEFAULT NOW()
);
CREATE SEQUENCE IF NOT EXISTS SEQ_TEAM_MEMBER_ID START WITH 1 INCREMENT BY 1;
CREATE TABLE T_RACK (
    id BIGINT DEFAULT random() PRIMARY KEY,
    serial_number VARCHAR(20) NOT NULL UNIQUE,
    team_id BIGINT REFERENCES T_TEAM(id),
    assembled_at DATE,
    created_at TIMESTAMP DEFAULT now(),
    modified_at TIMESTAMP DEFAULT now(),
    default_location VARCHAR(10),
    status VARCHAR(15)
    --status rack_status_enum
);
CREATE SEQUENCE IF NOT EXISTS SEQ_RACK_ID START WITH 1 INCREMENT BY 1;
CREATE TABLE T_RACK_ASSET(
     id BIGINT DEFAULT random() PRIMARY KEY,
     rack_id BIGINT REFERENCES T_RACK(id),
     asset_tag VARCHAR(10) NOT NULL UNIQUE
);
CREATE SEQUENCE IF NOT EXISTS SEQ_RACK_ASSET_ID START WITH 1 INCREMENT BY 1;
CREATE TABLE T_BOOKING(
      id BIGINT DEFAULT random() PRIMARY KEY,
      rack_id BIGINT REFERENCES T_RACK(id),
      requester_id BIGINT REFERENCES T_TEAM_MEMBER(id),
      book_from TIMESTAMP NOT NULL,
      book_to TIMESTAMP,
      created_at TIMESTAMP DEFAULT NOW(),
      modified_at TIMESTAMP DEFAULT NOW()
);
CREATE SEQUENCE IF NOT EXISTS SEQ_BOOKING_ID START WITH 1 INCREMENT BY 1;


