name: Docker Login
inputs:
  dockerhub_username:
    description: "dockerhub username"
    required: false
  dockerhub_password:
    description: "dockerhub password"

runs:
  using: composite
  steps:
    - name: login
      uses: docker/login-action@v3
      with:
        username: ${{inputs.dockerhub_username}}
        password: ${{inputs.dockerhub_password}}

    - name: push
      run: docker push ${{ ENV.DOCKER_IMAGE_NAME }}
      shell: bash


